### ISSUE TITLE
Put this version of preprocess on Pypi

### ISSUE THREAD

**Issue by ketch** [doconce/preprocess#1]
Please put this version on Pypi.  It would solve issues that I ran into today that prevented me from installing doconce:

https://github.com/hplgit/preprocess/issues/9

**Comment by KGHustad** [comment]
I have tried to contact Trent Mick, who has uploaded the version that's currently on PyPi, about this without getting an answer. I don't think there's any way to replace it without his cooperation.

**Comment by johannesring** [comment]
Yes sorry, my fault. I forgot that we do not own the package on PyPi.

**Comment by trentm** [comment]
@KGHustad has now been made an owner of the "preprocess" project on PyPI. Sorry for the delays in responding.
