### ISSUE TITLE
Regression with #include and -I option

### ISSUE THREAD

**Issue by claw111** [doconce/preprocess#3]
After having some spare time to resurrect a personal project of mine which uses preprocess, I upgraded from v1.1.0 to v1.2.3.

Found a regression with `#include` statements and providing include paths with the `-I` command-line option, whereby preprocess is no longer able to find the #include'd file in any of the include paths provided.  Preprocess errors out with a message similar to the following:
```
preprocess: error: could not find #include'd file "c.p.txt" on include path: ['include']
```

Steps to reproduce:
1. Create `a.p.txt` to have the following content:
```
BEFORE include
# #include "b.p.txt"
AFTER include
```
2. Create `includes/b.p.txt` to have the following content:
```
DURING include
```
3. Run preprocess from in the same directory as `a.p.txt`: `preprocess -I includes a.p.txt`
4. Observed output:
```
BEFORE include
preprocess: error: could not find #include'd file "b.p.txt" on include path: ['includes']
```
5. Expected output:
```
BEFORE include
DURING include
AFTER include
```

I believe the regression appeared in commit e937b3b where the `else: raise` statements were indented from the matching `for` statement to the matching `if` statement:
https://github.com/doconce/preprocess/blob/e937b3bbcdc3c8a576b8802745d0fa7af259c6d7/lib/preprocess.py#L497-L504

**Comment by KGHustad** [comment]
Thank you for the detailed report! Do you want to create a pull request yourself since you've already identified the changes that are required to solve this issue?

**Comment by claw111** [comment]
Normally I'd love to help out, but I have other priorities to focus on at the moment.
